[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-agent"
version = "0.1.0"

[tool.setuptools]
packages = ["mcp_agent"]
package-dir = {"mcp_agent" = "mcp_agent"}